name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t vue-app .

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag vue-app danisonediel/vue-app:latest
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push danisonediel/vue-app:latest
